<!DOCTYPE html>
<html><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all">
  <link href="/css/style.css" rel="stylesheet" type="text/css" media="all">
  <link href="/css/custom.css" rel="stylesheet" type="text/css" media="all">
  <script src="/js/bootstrap.bundle.min.js"></script>
  <link rel="apple-touch-icon" href="/logo.png" type="image/png">
  <link rel="icon" href="/img/logo.svg" type="image/svg+xml">
  <link rel="icon" href="/img/logo.png" type="image/png">
  <title>Bikulov&#39;s blog</title>
</head><body>
<header>
  <nav class="navbar navbar-expand navbar-dark volukib-header">
    <div class="container-fluid">
      <a class="navbar-brand" href="https://bikulov.org/"><img src="/img/logo.png" class="volukib-logo" alt="logo"> Bikulov&#39;s blog</a>
      <ul class="navbar-nav">
        
        <li class="nav-item">
          
          <a class="nav-link text-uppercase " href="/">Home</a>
        </li>
        
        <li class="nav-item">
          
          <a class="nav-link text-uppercase " href="/resume/">Resume</a>
        </li>
        
      </ul>
    </div>
  </nav>
</header><div class="container">
<div class="row text-center mb-5">
  <div class="col">
    <h1>throw() in function signature in C&#43;&#43;</h1>
    <div>2013-11-23</div>
    <div>
      
      <a class="" href="/tags/c&#43;&#43;">#c&#43;&#43;</a>
      
      <a class="" href="/tags/exceptions">#exceptions</a>
      
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <p><a href="http://www.cplusplus.com/doc/tutorial/exceptions/">There is</a> base class <code>exception</code> in standard library (header <code>&lt;exception&gt;</code>). It <a href="http://en.cppreference.com/w/cpp/error/exception">has</a> default constructor, copy constructor, copy operator and destructor and virtual <code>what()</code> function. Latter returns string with additional information about exception.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-cpp" data-lang="cpp"><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;exception&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e"></span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">MyException</span><span style="color:#f92672">:</span> <span style="color:#66d9ef">public</span> std<span style="color:#f92672">::</span>exception
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">virtual</span> <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">char</span><span style="color:#f92672">*</span> <span style="color:#a6e22e">what</span>() <span style="color:#66d9ef">const</span> <span style="color:#66d9ef">throw</span>()
</span></span><span style="display:flex;"><span>    {
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;My Exception happened&#34;</span>;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>}
</span></span></code></pre></div><p>The most confusing part in the above code is <code>throw()</code>. It assures no exception will be thrown from the <code>what()</code> function. For example, if you want to allow exception <code>int</code> and <code>float</code> to be raised in this function, you must write <code>throw(int,float)</code> (you can not do it in the above example, this fucntion definition is fixed in base class). Ok, this example is mostly unchangable, so let&rsquo;s write own <code>MyException</code> class without derivation from any standard library class.</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-cpp" data-lang="cpp"><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;string&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e"></span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">MyException</span>
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">public</span><span style="color:#f92672">:</span>
</span></span><span style="display:flex;"><span>    std<span style="color:#f92672">::</span>string what()
</span></span><span style="display:flex;"><span>    {
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;MyException happened&#34;</span>;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>};
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>(<span style="color:#66d9ef">int</span> argc, <span style="color:#66d9ef">char</span> <span style="color:#f92672">**</span>argv)
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span>    MyException a;
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span> {
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">throw</span> a;
</span></span><span style="display:flex;"><span>    } <span style="color:#66d9ef">catch</span> (MyException <span style="color:#f92672">&amp;</span>e) {
</span></span><span style="display:flex;"><span>        std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> e.what() <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
</span></span><span style="display:flex;"><span>    } <span style="color:#66d9ef">catch</span> (<span style="color:#66d9ef">int</span> a) {
</span></span><span style="display:flex;"><span>        std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;int thrown &#34;</span> <span style="color:#f92672">&lt;&lt;</span> a <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
</span></span><span style="display:flex;"><span>}
</span></span></code></pre></div><p>Ok, if you copy source code, compile and run it, you&rsquo;ll see:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-bash" data-lang="bash"><span style="display:flex;"><span>$ g++ main.cpp -o throw
</span></span><span style="display:flex;"><span>$ ./throw
</span></span><span style="display:flex;"><span>MyException happened
</span></span></code></pre></div><p>This behaviour is predictable. Exception thrown and caught by <code>catch (MyException &amp;e)</code>. No special modifiers is presented.</p>
<p>Lets change example a little (throwing exception from <code>what()</code>):</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-cpp" data-lang="cpp"><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;string&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e"></span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">MyException</span>
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">public</span><span style="color:#f92672">:</span>
</span></span><span style="display:flex;"><span>    std<span style="color:#f92672">::</span>string what()
</span></span><span style="display:flex;"><span>    {
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">throw</span> <span style="color:#ae81ff">10</span>;
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;MyException happened&#34;</span>;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>};
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>(<span style="color:#66d9ef">int</span> argc, <span style="color:#66d9ef">char</span> <span style="color:#f92672">**</span>argv)
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span> {
</span></span><span style="display:flex;"><span>        MyException a;
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">throw</span> a;
</span></span><span style="display:flex;"><span>    } <span style="color:#66d9ef">catch</span> (MyException <span style="color:#f92672">&amp;</span>e) {
</span></span><span style="display:flex;"><span>        std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> e.what() <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
</span></span><span style="display:flex;"><span>}
</span></span></code></pre></div><p>Throwing exception from <code>what()</code> causes unhandled exception:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-bash" data-lang="bash"><span style="display:flex;"><span>$ ./throw
</span></span><span style="display:flex;"><span>terminate called after throwing an instance of <span style="color:#e6db74">&#39;int&#39;</span>
</span></span><span style="display:flex;"><span>Aborted <span style="color:#f92672">(</span>core dumped<span style="color:#f92672">)</span>
</span></span></code></pre></div><p>Usage of throw() in function declaration is considered as a <a href="http://stackoverflow.com/questions/1055387/throw-keyword-in-functions-signature-c">bad idea</a>. But in this particular situation it is allowed: <code>what()</code> returns additional description, it must not send any other exception, as there is no guarantee this exception will behandled. Restrict exceptions from <code>what()</code>:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-cpp" data-lang="cpp"><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;iostream&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e">#include</span> <span style="color:#75715e">&lt;string&gt;</span><span style="color:#75715e">
</span></span></span><span style="display:flex;"><span><span style="color:#75715e"></span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">class</span> <span style="color:#a6e22e">MyException</span>
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">public</span><span style="color:#f92672">:</span>
</span></span><span style="display:flex;"><span>    std<span style="color:#f92672">::</span>string what() <span style="color:#66d9ef">throw</span>()
</span></span><span style="display:flex;"><span>    {
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">throw</span> <span style="color:#ae81ff">10</span>;
</span></span><span style="display:flex;"><span>        <span style="color:#66d9ef">return</span> <span style="color:#e6db74">&#34;MyException happened&#34;</span>;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>};
</span></span><span style="display:flex;"><span>
</span></span><span style="display:flex;"><span><span style="color:#66d9ef">int</span> <span style="color:#a6e22e">main</span>(<span style="color:#66d9ef">int</span> argc, <span style="color:#66d9ef">char</span> <span style="color:#f92672">**</span>argv)
</span></span><span style="display:flex;"><span>{
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">try</span> {
</span></span><span style="display:flex;"><span>        MyException a;
</span></span><span style="display:flex;"><span>        a.what();
</span></span><span style="display:flex;"><span>    } <span style="color:#66d9ef">catch</span> (...) {
</span></span><span style="display:flex;"><span>        std<span style="color:#f92672">::</span>cout <span style="color:#f92672">&lt;&lt;</span> <span style="color:#e6db74">&#34;exception handled&#34;</span> <span style="color:#f92672">&lt;&lt;</span> std<span style="color:#f92672">::</span>endl;
</span></span><span style="display:flex;"><span>    }
</span></span><span style="display:flex;"><span>    <span style="color:#66d9ef">return</span> <span style="color:#ae81ff">0</span>;
</span></span><span style="display:flex;"><span>}
</span></span></code></pre></div><p>Finally we get what we came from: this class is pretty like std::exception, isn&rsquo;t it? <code>throw()</code> ensures no exceptions can be sent from <code>show()</code> function. So, compiler will fail? No! Compiler reports no errors. But an error occures in runtime:</p>
<div class="highlight"><pre tabindex="0" style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4;"><code class="language-bash" data-lang="bash"><span style="display:flex;"><span>$ ./throw
</span></span><span style="display:flex;"><span>terminate called after throwing an instance of <span style="color:#e6db74">&#39;int&#39;</span>
</span></span><span style="display:flex;"><span>Aborted <span style="color:#f92672">(</span>core dumped<span style="color:#f92672">)</span>
</span></span></code></pre></div><p>There is a little information why the code have failed. No exception (even raised in functions called from <code>show()</code>) will pass through <code>show() throw()</code>. Error will appear only at runtime.</p>
<p>So, <code>throw()</code> is used to ensure no additional exceptions will be raised from <code>show()</code> function and will escape <code>catch()</code>. But in general case such behaviour is difficult to predict and <em>is</em> a bad practice. Try not to use <code>throw()</code> in function signature without high necessity. Try not to use throw with particular allowed exceptions (like <code>throw(A, B)</code>) in any situation. Standart <code>std::exception</code> is very good to derive your exceptions in huge amount of sutuations.</p>

  </div>
</div>

  </div><div class="container-fluid volukib-footer p-2">
  <footer class="text-center">
    <a class="text-decoration-none text-light" href="https://bikulov.org/">Bikulov&#39;s blog 2022</a>
  </footer>
</div></body>

</html>